version: '3.4'

services:
  dev-image:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/project
  worker-image:
    tty: true
    stdin_open: true
    command: bash -c "make && ./ava"
    build:
      context: .
      dockerfile: Dockerfile-worker
