apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    your_label: worker-headless-label
spec:
  selector:
    your_label: worker-headless-label
  ports:
    - port: 80
      name: transport
      protocol: TCP
  clusterIP: None