apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker-envars-fieldref-statefulset
  labels:
    app: worker-yaml
spec:
  serviceName: worker
  replicas: 2
  selector:
    matchLabels:
      app: worker-yaml
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker-yaml
    spec:
      containers:
        - name: tech-project-worker-image-z26m4
          image: tech-project_worker-image
          command:
            - /bin/sh
            - '-c'
          args:
            - >-
              while true; do echo -en '\n'; make; printenv MY_NODE_NAME MY_POD_NAME
              MY_POD_NAMESPACE; printenv MY_POD_IP MY_POD_SERVICE_ACCOUNT; sleep
              10; done;
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxUnavailable: 25%
#      maxSurge: 25%
  revisionHistoryLimit: 10
#  progressDeadlineSeconds: 600